#!/bin/sh
# https://github.com/shyiko/ktlint pre-commit hook

if git diff --name-only --cached --relative | grep '\.kt[s"]\?$' | xargs ktlint -F --relative .; then exit 1
else
    git diff --name-only --cached --relative | grep '\.kt[s"]\?$' | xargs java -jar ktlint -F --relative .
fi
